onlinexam/urls.py
from django.urls import path,include
from django.contrib import admin
from exam import views
from django.contrib.auth.views import LogoutView,LoginView
urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    


    path('',views.home_view,name=''),
    path('logout', LogoutView.as_view(template_name='exam/logout.html'),name='logout'),
    path('contactus_view', views.contactus_view),
    path('afterlogin', views.afterlogin_view,name='afterlogin'),



    path('adminclick', views.adminclick_view),
    path('adminlogin', LoginView.as_view(template_name='exam/adminlogin.html'),name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),


    path('admin-student', views.admin_student_view,name='admin-student'),
    path('admin-view-student', views.admin_view_student_view,name='admin-view-student'),
    path('admin-view-student-marks', views.admin_view_student_marks_view,name='admin-view-student-marks'),
    path('admin-view-marks/<int:pk>', views.admin_view_marks_view,name='admin-view-marks'),
    path('admin-check-marks/<int:pk>', views.admin_check_marks_view,name='admin-check-marks'),
    path('update-student/<int:pk>', views.update_student_view,name='update-student'),
    path('delete-student/<int:pk>', views.delete_student_view,name='delete-student'),

    path('admin-course', views.admin_course_view,name='admin-course'),
    path('admin-add-course', views.admin_add_course_view,name='admin-add-course'),
    path('admin-view-course', views.admin_view_course_view,name='admin-view-course'),
    path('admin-view-request/<int:course_id>/', views.admin_view_request, name='admin-view-request'),
    path('delete-course/<int:pk>', views.delete_course_view,name='delete-course'),

    path('admin-question', views.admin_question_view,name='admin-question'),
    path('admin-add-question', views.admin_add_question_view,name='admin-add-question'),
    path('admin-view-question', views.admin_view_question_view,name='admin-view-question'),
    path('view-question/<int:pk>', views.view_question_view,name='view-question'),
    path('view-all-question/<int:pk>', views.view_all_questions,name='view-all-question'),
    path('delete-question/<int:pk>', views.delete_question_view,name='delete-question'),


    path('add-exam-content-view', views.add_exam_content_view, name='add-exam-content-view'),
    path('view-exam-content-view', views.view_exam_content_view, name='add-exam-content-view'),
    path('view-delete-content/<int:course_id>/', views.view_delete_content, name='view-delete-content'),
    path('delete-content/<int:pk>/<int:course_id>/', views.delete_content, name='delete-content'),
    path('view-study-progress', views.view_study_progress, name='view-study-progress'),
    path('study-progress-view/<int:student_id>/', views.study_progress_view, name='study-progress-view'),
    path("views_student", views.views_student, name = "views_student"),
]

student/urls.py
from django.urls import path
from student import views
from django.contrib.auth.views import LoginView

urlpatterns = [
path('studentclick', views.studentclick_view),
path('studentlogin', LoginView.as_view(template_name='student/studentlogin.html'),name='studentlogin'),
path('studentsignup', views.student_signup_view,name='studentsignup'),
path('student-dashboard', views.student_dashboard_view,name='student-dashboard'),
path('student-exam', views.student_exam_view,name='student-exam'),
path('take-exam/<int:pk>', views.take_exam_view,name='take-exam'),
path('start-exam/<int:pk>', views.start_exam_view,name='start-exam'),

path('calculate-marks', views.calculate_marks_view,name='calculate-marks'),
path('view-result', views.view_result_view,name='view-result'),
path('view-result-detail/<int:result_id>/', views.view_result_detail_view,name='view-result-detail'),
path('check-marks/<int:pk>', views.check_marks_view,name='check-marks'),
path('student-marks', views.student_marks_view,name='student-marks'),
path('study-progress-student/<int:student_id>/', views.study_progress_student, name='study-progress-student'),
]

exam/models.py
from django.db import models
from student.models import Student
from django.utils import timezone
class Course(models.Model):
   course_name = models.CharField(max_length=50)
   question_number = models.PositiveIntegerField()
   total_marks = models.PositiveIntegerField()
   exam_requirement = models.TextField(blank=True, null=True)  # Thêm trường mới để lưu nội dung cần đạt
   def __str__(self):
        return self.course_name

class Question(models.Model):
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    marks=models.PositiveIntegerField()
    question=models.CharField(max_length=600)
    option1=models.CharField(max_length=200)
    option2=models.CharField(max_length=200)
    option3=models.CharField(max_length=200)
    option4=models.CharField(max_length=200)
    cat=(('Option1','Option1'),('Option2','Option2'),('Option3','Option3'),('Option4','Option4'))
    DIFFICULTY_CHOICES= [
        ('biet', 'Biết'),
        ('hieu', 'Hiểu'),
        ('van_dung_thap', 'Vận dụng thấp'),
        ('van_dung_cao', 'Vận dụng cao'),
    ]
    answer=models.CharField(max_length=200,choices=cat)
    difficulty_level= models.CharField(max_length=20, choices=DIFFICULTY_CHOICES, default='biet')

class Result(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    exam = models.ForeignKey(Course,on_delete=models.CASCADE)
    marks = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.student}, {self.exam}, {self.marks}, {self.date}"

class ExamContent(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Khóa học')
    exam_requirement = models.TextField()

    def __str__(self):
        return f"{self.course.course_name} - Yêu cầu kỳ thi"


class StudyProgress(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    progress_percentage = models.PositiveIntegerField(default=0)
    last_updated = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.student.user.username} - {self.course.course_name} - {self.progress_percentage}%"

student/models.py
from django.db import models
from django.contrib.auth.models import User

class Student(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic= models.ImageField(upload_to='profile_pic/Student/',null=True,blank=True)
    address = models.CharField(max_length=40)
    mobile = models.CharField(max_length=20,null=False)
   
    @property
    def get_name(self):
        return self.user.first_name+" "+self.user.last_name
    @property
    def get_instance(self): 
        return self
    def __str__(self):
        return f"{self.user.first_name}, {self.user.id}"

student/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models
from exam import models as QMODEL

class StudentUserForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['first_name','last_name','username','password']
        widgets = {
        'password': forms.PasswordInput()
        }

class StudentForm(forms.ModelForm):
    class Meta:
        model=models.Student
        fields=['address','mobile','profile_pic']

student/views.py
from django.shortcuts import render,redirect,reverse
from . import forms,models
from django.db.models import Sum
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required,user_passes_test
from django.conf import settings
from datetime import date, timedelta
from exam import models as QMODEL
from django.contrib.auth.models import User
from .models import  Student
from django.shortcuts import get_object_or_404

#for showing signup/login button for student
def studentclick_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    return render(request,'student/studentclick.html')

def student_signup_view(request):
    userForm=forms.StudentUserForm()
    studentForm=forms.StudentForm()
    mydict={'userForm':userForm,'studentForm':studentForm}
    if request.method=='POST':
        userForm=forms.StudentUserForm(request.POST)
        studentForm=forms.StudentForm(request.POST,request.FILES)
        if userForm.is_valid() and studentForm.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            student=studentForm.save(commit=False)
            student.user=user
            student.save()
            my_student_group = Group.objects.get_or_create(name='STUDENT')
            my_student_group[0].user_set.add(user)
        return HttpResponseRedirect('studentlogin')
    return render(request,'student/studentsignup.html',context=mydict)

def is_student(user):
    return user.groups.filter(name='STUDENT').exists()

@login_required(login_url='studentlogin')
@user_passes_test(is_student)
def student_dashboard_view(request):
    print(QMODEL.Student.objects.all())
    dict={
    "student": QMODEL.Student.objects.get(user = User.objects.get(id = request.user.id)),
    'total_course':QMODEL.Course.objects.all().count(),
    'total_question':QMODEL.Question.objects.all().count(),
    }
    return render(request,'student/student_dashboard.html',context=dict)

@login_required(login_url='studentlogin')
@user_passes_test(is_student)
def student_exam_view(request):
    courses=QMODEL.Course.objects.all()
    return render(request,'student/student_exam.html',{'courses':courses})

@login_required(login_url='studentlogin')
@user_passes_test(is_student)
def take_exam_view(request,pk):
    course=QMODEL.Course.objects.get(id=pk)
    total_questions=QMODEL.Question.objects.all().filter(course=course).count()
    questions=QMODEL.Question.objects.all().filter(course=course)
    total_marks=0
    for q in questions:
        total_marks=total_marks + q.marks
    
    return render(request,'student/take_exam.html',{'course':course,'total_questions':total_questions,'total_marks':total_marks})

@login_required(login_url='studentlogin')
@user_passes_test(is_student)
def start_exam_view(request,pk):
    course=QMODEL.Course.objects.get(id=pk)
    questions=QMODEL.Question.objects.all().filter(course=course)
    if request.method=='POST':
        pass
    response= render(request,'student/start_exam.html',{'course':course,'questions':questions})
    response.set_cookie('course_id',course.id)
    return response


@login_required(login_url='studentlogin')
@user_passes_test(is_student)
def calculate_marks_view(request):
    try:
        course_id = request.COOKIES.get('course_id')

        if course_id is not None:
            course = QMODEL.Course.objects.get(id=course_id)
            total_marks = 0
            progress_percentage = 0
            questions = QMODEL.Question.objects.filter(course=course)
            print("Số lượng câu hỏi:", len(questions))

            for i, question in enumerate(questions):
                selected_ans = request.COOKIES.get(str(i + 1))
                print("Câu trả lời đã chọn:", selected_ans)
                actual_answer = question.answer
                print("Câu trả lời đúng:", actual_answer)

                if selected_ans is not None and selected_ans == actual_answer:
                    total_marks += question.marks

            if request.user and request.user.id:
                student = Student.objects.get(user_id=request.user.id)
                result = QMODEL.Result()
                result.marks = total_marks
                print("Tổng điểm:", total_marks)
                result.exam = course
                result.student = student
                result.save()

                progress_check = QMODEL.StudyProgress.objects.filter(student=student, course=course).exists()

                if progress_check:  # tức đã tồn tại
                    progress = QMODEL.StudyProgress.objects.filter(student=student, course=course).first()
                    count_questions = QMODEL.Question.objects.filter(course=course).count()
                    progress.progress_percentage = total_marks / count_questions * 100
                    progress.save()
                else:
                    progress = QMODEL.StudyProgress()
                    progress.student = student
                    progress.course = course
                    count_questions = QMODEL.Question.objects.filter(course=course).count()
                    progress.progress_percentage = total_marks / count_questions * 100
                    progress.save()

    except QMODEL.Course.DoesNotExist:
        # Xử lý trường hợp không tìm thấy khóa học
        pass
    except Student.DoesNotExist:
        # Xử lý trường hợp không tìm thấy sinh viên
        pass

    return HttpResponseRedirect('view-result') 


@login_required(login_url='studentlogin')
@user_passes_test(is_student)
def view_result_view(request):
    courses=QMODEL.Course.objects.all()
    return render(request,'student/view_result.html',{'courses':courses})

  
login_required(login_url='studentlogin')
@user_passes_test(is_student)
def check_marks_view(request,pk):
    course=QMODEL.Course.objects.get(id=pk)
    student = models.Student.objects.get(user_id=request.user.id)
    results= QMODEL.Result.objects.all().filter(exam=course).filter(student=student)
    return render(request,'student/check_marks.html',{'results':results})

@login_required(login_url='studentlogin')
@user_passes_test(is_student)
def student_marks_view(request):
    courses=QMODEL.Course.objects.all()
    return render(request,'student/student_marks.html',{'courses':courses})



@login_required(login_url='studentlogin')
@user_passes_test(is_student)
def view_result_detail_view(request, result_id):
    result = QMODEL.Result.objects.get(id=result_id)
    print("result",result)
    # Lấy danh sách câu hỏi của bài kiểm tra
    questions = QMODEL.Question.objects.filter(course=result.exam)
    print("questions",questions)
    # Lấy các câu trả lời đã chọn bởi sinh viên
    selected_answers =[]
    for i in range(len(questions)):     #duyệt câu hỏi
        selected_answers.append(request.COOKIES.get(str(i+1)))  
    print("các câu trả lời đã chọn bởi sinh viên",len(selected_answers))
    # Tạo danh sách chứa thông tin chi tiết về từng câu hỏi
    question_details = []
    count = 0 
    for question in questions:
        is_correct = question.answer == selected_answers[count]
        #Hiện nội dung từng option
        correct_answer = None
        if question.answer == "Option1":
            correct_answer = question.option1
        elif question.answer == "Option2":
            correct_answer = question.option2
        elif question.answer == "Option3":
            correct_answer = question.option3
        elif question.answer == "Option4":
            correct_answer = question.option4
        selected_answer = None
        if selected_answers[count] == "Option1":
            selected_answer = question.option1
        elif selected_answers[count] == "Option2":
            selected_answer = question.option2
        elif selected_answers[count] == "Option3":
            selected_answer = question.option3
        elif selected_answers[count] == "Option4":
            selected_answer = question.option4
        question_details.append({
            'question_text': question.question,
            'selected_answer': selected_answer,
            'correct_answer': correct_answer,
            'is_correct': is_correct,
        })
        count += 1
    # Truyền thông tin chi tiết vào template để hiển thị
    context = {
        'result': result,
        'question_details': question_details,
    }
    return render(request, 'student/view_result_detail.html', context)



@login_required(login_url='studentlogin') 
def study_progress_student(request, student_id): # tiến trình của mỗi em học sinh
    student = models.Student.objects.get(id= student_id)
    courses = QMODEL.Course.objects.all()
    progress_data = []
    print("course", courses)
    for course in courses:
        progress, created = QMODEL.StudyProgress.objects.get_or_create(student=student, course=course)
        progress_data.append({
            'course': course,
            'progress': progress,
        })
        print("progress_data", progress_data)

    return render(request, 'student/study_progress.html', {'student': student, 'progress_data': progress_data})

templates/student/check_marks.html
{% extends 'student/studentbase.html' %}
{% block content %}
{% load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <title>HCMUE</title>
  <link  href="https://th.bing.com/th/id/OIP._2unhUk9v8d-QsxMjcKMxgHaDm?rs=1&pid=ImgDetMain.png" rel="shortcut icon">

  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary rounded-0">
    <div class="panel-heading rounded-0">
      <h6 class="panel-title">Điểm của tôi</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr>
          <th class="text-center">Khóa học</th>
          <th class="text-center">Tổng điểm</th>
          <th class="text-center">Số lần tham gia</th>
          <th class="text-center">Ngày kiểm tra</th>
          <th class="text-center">Hành động</th>
        </tr>
      </thead>
      {% for t in results %}
      <tr>
        <td class="text-center"> {{t.exam}}</td>
        <td class="text-center"> {{t.marks}}</td>
        <td class="text-center"> {{ forloop.counter }}</td>
        <td class="text-center"> {{t.date}}</td>
        <td class='text-center'><a class="btn btn-dark btn-sm" style="border-radius:0px;" href="{% url 'view-result-detail' t.id %}"><span class="glyphicon glyphicon-eye-open"></span> Xem</a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}

templates/student/start_exam.html
{% extends 'student/studentbase.html' %} {% block content %} {%load static%}

<head>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


</head>


<div class="jumbotron my-4">

    <form class="form" autocomplete="off" onsubmit="return saveAns()" action="/student/calculate-marks" method="POST">
        {% csrf_token %}
        <h2 style="text-align: center;">Khóa học: {{course.course_name}}</h2>
        {% for q in questions%}
        <div class="d-flex w-100 align-items-center">
            <div class="col-auto flex-shrink-1 flex-grow-1">
                <h3 class="">{{ forloop.counter }}. {{q.question}}</h3>
            </div>
            <div class="col-auto">
                <h4 style="text-align: right;">[{{q.marks}} Điểm]</h4>
            </div>
        </div>
        <input type="hidden" name="csrfmiddlewaretoken" value="C24rUotmdHawVQJL3KrqiWxvti8UffOFYUc8TRbZtLt36AVLdP3jbkzUVe3beRAa">


        <div class="form-check mx-4 d-flex align-items-center">
            <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{q.option1}}" value="Option1">
            <label class="form-check-label ml-3" for="option1">
              {{q.option1}}
            </label>
        </div>


        <div class="form-check mx-4 d-flex align-items-center">
            <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{q.option2}}" value="Option2">
            <label class="form-check-label ml-3" for="option2">
              {{q.option2}}
            </label>
        </div>


        <div class="form-check mx-4 d-flex align-items-center">
            <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{q.option3}}" value="Option3">
            <label class="form-check-label ml-3" for="option3">
              {{q.option3}}
            </label>
        </div>


        <div class="form-check mx-4 d-flex align-items-center">
            <input class="form-check-input" type="radio" name="{{ forloop.counter }}" id="{{q.option4}}" value="Option4">
            <label class="form-check-label ml-3" for="option4">
              {{q.option4}}
            </label>
        </div>

        {% endfor %}
        <input class="btn btn-primary btn-lg" style="border-radius: 0%;" type="submit" value="Nộp bài">
    </form>
</div>

<script>
    function saveAns() {

        var ele = document.getElementsByTagName('input');
        for (i = 0; i < ele.length; i++) {
            if (ele[i].type = "radio") {
                if (ele[i].checked) {
                    setCookie(ele[i].name, ele[i].value, 3)
                }
            }
        }

    }

    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires=" + d.toUTCString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }
</script>

<br><br><br><br><br><br> {% endblock content %}

templates/student/student_dashboard.html
{% extends 'student/studentbase.html' %}
{% load widget_tweaks %}
{% block content %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>HCMUE</title>
    <link  href="https://th.bing.com/th/id/OIP._2unhUk9v8d-QsxMjcKMxgHaDm?rs=1&pid=ImgDetMain.png" rel="shortcut icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <style type="text/css">
      a:link {
        text-decoration: none;
      }
  
      .order-card {
        color: rgb(255, 255, 255);
      }
  
      .bg-c-blue {
        background: #104f66;
      }
  
      .bg-c-green {
        background:#4C51BF;
      }
  
      .bg-c-yellow {
        background: #53616e;
      }
  
      .bg-c-pink {
        background: #663a30;
      }
  
  
      .card {
        
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
      }
  
      .card .card-block {
        padding: 25px;
      }
  
      .order-card i {
        font-size: 26px;
      }
  
      .f-left {
        float: left;
      }
  
      .f-right {
        float: right;
      }
      header {
      left: 0px;
      right: 0px;
    }
    </style>
  </head>
<br><br>

  <div class="container">
    <div class="row">
      
  
      <div class="col-md-4 col-xl-6">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20">Các bài kiểm tra có sẵn</h6>
           <h2 class="text-right"><i class="fas fa-book f-left"></i><span>{{total_course}}</span></h2>
          </div>
        </div>
      </div>
  
      <div class="col-md-4 col-xl-6">
        <div class="card bg-c-yellow order-card">
          <div class="card-block">
            <h6 class="m-b-20">Tổng số câu hỏi</h6>
            <h2 class="text-right"><i class="fas fa-question-circle f-left"></i><span>{{total_question}}</span></h2>
            
          </div>
        </div>
      </div>

      <div class="col-md-4 col-xl-6">
        <div class="card bg-c-blue order-card">
          <a href= "{% url  'study-progress-student' student.id   %}"  style="text-decoration: none;color:white;">
          <div class="card-block">
            <h6 class="m-b-20">Xem tiến độ </h6>
            <h2 class="text-right"><i class="fa-solid fa-bars-progress f-left"></i><span><i class="fas fa-eye"></i></span></h2>
          </div>
        </div>
      </div>
    </div>
  </div>


<br><br><br><br><br><br><br><br><br><br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>


{% endblock content %}

templates/student/take_exam.html
{% extends 'student/studentbase.html' %}
{% block content %}
{% load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  <title>HCMUE</title>
  <link  href="https://th.bing.com/th/id/OIP._2unhUk9v8d-QsxMjcKMxgHaDm?rs=1&pid=ImgDetMain.png" rel="shortcut icon">

</head>

<div class="container my-4">
    <div class="jumbotron">
        <div class="row">
            <div class="card border-primary mx-4 my-4">
                <div class="card-body text-default">

                    <h4 class="card-title">Tổng quan bài kiểm tra: </h4>
                    <p class="card-text">
                        </p><ul style="list-style:decimal;">
                            <li>Khóa học: {{course.course_name}}</li>
                            <li>Tổng số câu hỏi: {{total_questions}}</li>
                            <li>Điểm: {{total_marks}}</li>
                        </ul>
                    <p></p>
                    {% with exam_contents=course.examcontent_set.all %}
                    {% if exam_contents %}
                        <div>
                            <label>Yêu cầu cần đạt:</label>
                            <ul>
                                {% for exam_content in exam_contents %}
                                    {{ exam_content.exam_requirement }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% else %}
                        <p>Chưa có yêu cầu cần đạt cho kỳ thi này.</p>
                    {% endif %}
                {% endwith %}


                    <h4 class="card-title"> <strong >Lưu ý: </h4> </strong>
                    <p class="card-text">
                        </p><ul style="list-style:decimal;">
                            <li>Tất cả câu hỏi là câu trắc nghiệm</li>
                            <li><span class="text-danger">Chỉ có một lựa chọn là chính xác trong số những lựa chọn đã cho.</span></li>
                            <li>Mỗi câu hỏi mang số điểm khác nhau.</li>
                            <li>Cố gắng trả lời càng SỚM càng TỐT.</li>
                            <li>Nếu bạn NHẤN làm mới hoặc quay lại trang trước, sẽ có một câu hỏi mới cho bạn và câu hỏi bạn đang trả lời sẽ được tính là số lần tham gia.</li>
                            <li>Các câu hỏi được trình bày ngẫu nhiên.</li>
                            <li>Bạn sẽ có thể xem điểm ngay lập tức một lần sau khi bạn gửi câu trả lời.</li>
                        </ul>
                    <p></p>
                    <a href="{% url 'start-exam' course.id  %}" class="btn btn-primary btn-lg" style="border-radius:0px;margin-left: 400px">Kiểm tra</a>
                </div>  
                <div class="card-footer">Chúc các bạn thi tốt.</div>  
            </div>  
        </div>  

    </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}