onlinexam/urls.py
from django.urls import path,include
from django.contrib import admin
from exam import views
from django.contrib.auth.views import LogoutView,LoginView
urlpatterns = [
   
    path('admin/', admin.site.urls),
    path('student/',include('student.urls')),
    


    path('',views.home_view,name=''),
    path('logout', LogoutView.as_view(template_name='exam/logout.html'),name='logout'),
    path('contactus_view', views.contactus_view),
    path('afterlogin', views.afterlogin_view,name='afterlogin'),



    path('adminclick', views.adminclick_view),
    path('adminlogin', LoginView.as_view(template_name='exam/adminlogin.html'),name='adminlogin'),
    path('admin-dashboard', views.admin_dashboard_view,name='admin-dashboard'),


    path('admin-student', views.admin_student_view,name='admin-student'),
    path('admin-view-student', views.admin_view_student_view,name='admin-view-student'),
    path('admin-view-student-marks', views.admin_view_student_marks_view,name='admin-view-student-marks'),
    path('admin-view-marks/<int:pk>', views.admin_view_marks_view,name='admin-view-marks'),
    path('admin-check-marks/<int:pk>', views.admin_check_marks_view,name='admin-check-marks'),
    path('update-student/<int:pk>', views.update_student_view,name='update-student'),
    path('delete-student/<int:pk>', views.delete_student_view,name='delete-student'),

    path('admin-course', views.admin_course_view,name='admin-course'),
    path('admin-add-course', views.admin_add_course_view,name='admin-add-course'),
    path('admin-view-course', views.admin_view_course_view,name='admin-view-course'),
    path('admin-view-request/<int:course_id>/', views.admin_view_request, name='admin-view-request'),
    path('delete-course/<int:pk>', views.delete_course_view,name='delete-course'),

    path('admin-question', views.admin_question_view,name='admin-question'),
    path('admin-add-question', views.admin_add_question_view,name='admin-add-question'),
    path('admin-view-question', views.admin_view_question_view,name='admin-view-question'),
    path('view-question/<int:pk>', views.view_question_view,name='view-question'),
    path('view-all-question/<int:pk>', views.view_all_questions,name='view-all-question'),
    path('delete-question/<int:pk>', views.delete_question_view,name='delete-question'),


    path('add-exam-content-view', views.add_exam_content_view, name='add-exam-content-view'),
    path('view-exam-content-view', views.view_exam_content_view, name='add-exam-content-view'),
    path('view-delete-content/<int:course_id>/', views.view_delete_content, name='view-delete-content'),
    path('delete-content/<int:pk>/<int:course_id>/', views.delete_content, name='delete-content'),
    path('view-study-progress', views.view_study_progress, name='view-study-progress'),
    path('study-progress-view/<int:student_id>/', views.study_progress_view, name='study-progress-view'),
    path("views_student", views.views_student, name = "views_student"),
]

student/urls.py
from django.urls import path
from student import views
from django.contrib.auth.views import LoginView

urlpatterns = [
path('studentclick', views.studentclick_view),
path('studentlogin', LoginView.as_view(template_name='student/studentlogin.html'),name='studentlogin'),
path('studentsignup', views.student_signup_view,name='studentsignup'),
path('student-dashboard', views.student_dashboard_view,name='student-dashboard'),
path('student-exam', views.student_exam_view,name='student-exam'),
path('take-exam/<int:pk>', views.take_exam_view,name='take-exam'),
path('start-exam/<int:pk>', views.start_exam_view,name='start-exam'),

path('calculate-marks', views.calculate_marks_view,name='calculate-marks'),
path('view-result', views.view_result_view,name='view-result'),
path('view-result-detail/<int:result_id>/', views.view_result_detail_view,name='view-result-detail'),
path('check-marks/<int:pk>', views.check_marks_view,name='check-marks'),
path('student-marks', views.student_marks_view,name='student-marks'),
path('study-progress-student/<int:student_id>/', views.study_progress_student, name='study-progress-student'),
]

exam/models.py
from django.db import models
from student.models import Student
from django.utils import timezone
class Course(models.Model):
   course_name = models.CharField(max_length=50)
   question_number = models.PositiveIntegerField()
   total_marks = models.PositiveIntegerField()
   exam_requirement = models.TextField(blank=True, null=True)  # Thêm trường mới để lưu nội dung cần đạt
   def __str__(self):
        return self.course_name

class Question(models.Model):
    course=models.ForeignKey(Course,on_delete=models.CASCADE)
    marks=models.PositiveIntegerField()
    question=models.CharField(max_length=600)
    option1=models.CharField(max_length=200)
    option2=models.CharField(max_length=200)
    option3=models.CharField(max_length=200)
    option4=models.CharField(max_length=200)
    cat=(('Option1','Option1'),('Option2','Option2'),('Option3','Option3'),('Option4','Option4'))
    DIFFICULTY_CHOICES= [
        ('biet', 'Biết'),
        ('hieu', 'Hiểu'),
        ('van_dung_thap', 'Vận dụng thấp'),
        ('van_dung_cao', 'Vận dụng cao'),
    ]
    answer=models.CharField(max_length=200,choices=cat)
    difficulty_level= models.CharField(max_length=20, choices=DIFFICULTY_CHOICES, default='biet')

class Result(models.Model):
    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    exam = models.ForeignKey(Course,on_delete=models.CASCADE)
    marks = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.student}, {self.exam}, {self.marks}, {self.date}"

class ExamContent(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name='Khóa học')
    exam_requirement = models.TextField()

    def __str__(self):
        return f"{self.course.course_name} - Yêu cầu kỳ thi"


class StudyProgress(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    progress_percentage = models.PositiveIntegerField(default=0)
    last_updated = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"{self.student.user.username} - {self.course.course_name} - {self.progress_percentage}%"

exam/forms.py
from django import forms
from django.contrib.auth.models import User
from . import models

class ContactusForm(forms.Form):
    Name = forms.CharField(max_length=30)
    Email = forms.EmailField()
    Message = forms.CharField(max_length=500,widget=forms.Textarea(attrs={'rows': 3, 'cols': 30}))


class CourseForm(forms.ModelForm):
    class Meta:
        model=models.Course
        fields=['course_name','question_number','total_marks','exam_requirement']
     

class QuestionForm(forms.ModelForm):
    courseID=forms.ModelChoiceField(queryset=models.Course.objects.all(),empty_label="Tên khóa học", to_field_name="id")
    class Meta:
        model=models.Question
        fields=['marks','question','option1','option2','option3','option4','answer','difficulty_level']
        widgets = {
            'question': forms.Textarea(attrs={'rows': 4, 'cols': 60})
        }


class ExamContentForm(forms.ModelForm):
    courseID=forms.ModelChoiceField(queryset=models.Course.objects.all(),empty_label="Tên khóa học", to_field_name="id")
    class Meta:
        model = models.ExamContent
        fields = ['exam_requirement']
        labels = {
            'exam_requirement': 'Yêu cầu cần đạt',
        }
        widgets = {
            'exam_requirement': forms.Textarea(attrs={'rows': 4, 'cols': 60}),
        }

exam/views.py
from django.shortcuts import get_object_or_404, render,redirect,reverse
from . import forms,models
from django.db.models import Sum
from django.contrib.auth.models import Group
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required,user_passes_test
from django.conf import settings
from datetime import date, timedelta
from django.core.mail import send_mail
from student import models as SMODEL
from student import forms as SFORM
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db.models import Count
from .forms import ExamContentForm
from .models import ExamContent
from .models import StudyProgress
from .models import  Student




def home_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')  
    return render(request,'exam/index.html')

def is_student(user):
    return user.groups.filter(name='STUDENT').exists()
 

def afterlogin_view(request):
    if is_student(request.user):      
        return redirect('student/student-dashboard')
    else:
        return redirect('admin-dashboard')



def adminclick_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect('afterlogin')
    return HttpResponseRedirect('adminlogin')


@login_required(login_url='adminlogin')
def admin_dashboard_view(request):
    dict={
    'total_student':SMODEL.Student.objects.all().count(),
    'total_course':models.Course.objects.all().count(),
    'total_question':models.Question.objects.all().count(),
    }
    return render(request,'exam/admin_dashboard.html',context=dict)




@login_required(login_url='adminlogin')
def admin_student_view(request):
    dict={
        'total_student':SMODEL.Student.objects.all().count(),
    }
    return render(request,'exam/admin_student.html',context=dict)

@login_required(login_url='adminlogin')
def admin_view_student_view(request):
    students= SMODEL.Student.objects.all()
    return render(request,'exam/admin_view_student.html',{'students':students})



@login_required(login_url='adminlogin')
def update_student_view(request,pk):
    student=SMODEL.Student.objects.get(id=pk)
    user=SMODEL.User.objects.get(id=student.user_id)
    userForm=SFORM.StudentUserForm(instance=user)
    studentForm=SFORM.StudentForm(request.FILES,instance=student)
    mydict={'userForm':userForm,'studentForm':studentForm}
    if request.method=='POST':
        userForm=SFORM.StudentUserForm(request.POST,instance=user)
        studentForm=SFORM.StudentForm(request.POST,request.FILES,instance=student)
        if userForm.is_valid() and studentForm.is_valid():
            user=userForm.save()
            user.set_password(user.password)
            user.save()
            studentForm.save()
            return redirect('admin-view-student')
    return render(request,'exam/update_student.html',context=mydict)



@login_required(login_url='adminlogin')
def delete_student_view(request,pk):
    student=SMODEL.Student.objects.get(id=pk)
    user=User.objects.get(id=student.user_id)
    user.delete()
    student.delete()
    return HttpResponseRedirect('/admin-view-student')


@login_required(login_url='adminlogin')
def admin_course_view(request):
    return render(request,'exam/admin_course.html')


@login_required(login_url='adminlogin')
def admin_add_course_view(request):
    courseForm=forms.CourseForm()
    if request.method=='POST':
        courseForm=forms.CourseForm(request.POST)
        if courseForm.is_valid():        
            courseForm.save()
        else:
            print("form is invalid")
        return HttpResponseRedirect('/admin-view-course')
    return render(request,'exam/admin_add_course.html',{'courseForm':courseForm})


@login_required(login_url='adminlogin')
def admin_view_course_view(request):
    courses = models.Course.objects.all()
    return render(request,'exam/admin_view_course.html',{'courses':courses})

@login_required(login_url='adminlogin')
def delete_course_view(request,pk):
    course=models.Course.objects.get(id=pk)
    course.delete()
    return HttpResponseRedirect('/admin-view-course')



@login_required(login_url='adminlogin')
def admin_question_view(request):
    return render(request,'exam/admin_question.html')


@login_required(login_url='adminlogin')
def admin_add_question_view(request):
    questionForm=forms.QuestionForm()
    if request.method=='POST':
        questionForm=forms.QuestionForm(request.POST)
        if questionForm.is_valid():
            question=questionForm.save(commit=False)
            course=models.Course.objects.get(id=request.POST.get('courseID'))
            question.course=course
            question.save()       
        else: 
            print("form is invalid")
        return HttpResponseRedirect('/admin-view-question')
    return render(request,'exam/admin_add_question.html',{'questionForm':questionForm})


@login_required(login_url='adminlogin')
def admin_view_question_view(request):
    courses= models.Course.objects.all()
    return render(request,'exam/admin_view_question.html',{'courses':courses})

@login_required(login_url='adminlogin')
def view_question_view(request,pk):
    questions=models.Question.objects.all().filter(course_id=pk)
    return render(request,'exam/view_question.html',{'questions':questions})

@login_required(login_url='adminlogin')
def delete_question_view(request,pk):
    question=models.Question.objects.get(id=pk)
    question.delete()
    return HttpResponseRedirect('/admin-view-question')

@login_required(login_url='adminlogin')
def admin_view_student_marks_view(request):
    students= SMODEL.Student.objects.all()
    return render(request,'exam/admin_view_student_marks.html',{'students':students})

@login_required(login_url='adminlogin')
def admin_view_marks_view(request,pk):
    courses = models.Course.objects.all()
    response =  render(request,'exam/admin_view_marks.html',{'courses':courses})
    response.set_cookie('student_id',str(pk))
    return response


#Xem điểm
@login_required(login_url='adminlogin')
def admin_check_marks_view(request,pk):
    course = models.Course.objects.get(id=pk)
    student_id = request.COOKIES.get('student_id')
    student= SMODEL.Student.objects.get(id=student_id)
    results= models.Result.objects.all().filter(exam=course).filter(student=student)
    return render(request,'exam/admin_check_marks.html',{'results':results})
    


def aboutus_view(request):
    return render(request,'exam/aboutus.html')

#Trang liên hệ
def contactus_view(request):
    sub = forms.ContactusForm()
    if request.method == 'POST':
        sub = forms.ContactusForm(request.POST)
        if sub.is_valid():
            email = sub.cleaned_data['Email']
            name=sub.cleaned_data['Name']
            message = sub.cleaned_data['Message']
            send_mail(str(name)+' || '+str(email),message,settings.EMAIL_HOST_USER, settings.EMAIL_RECEIVING_USER, fail_silently = False)
            return render(request, 'exam/contactussuccess.html')
    return render(request, 'exam/contactus.html', {'form':sub})

#Xem mức độ YCCĐ
@login_required(login_url='adminlogin')
def admin_view_request(request, course_id):
    # Lấy đối tượng Course
    course_instance = models.Course.objects.get(id=course_id)

    # Tạo một dictionary để lưu tổng số câu hỏi cho mỗi mức độ khó khăn
    difficulty_data = {
        'biet': course_instance.question_set.filter(difficulty_level='biet').count(),
        'hieu': course_instance.question_set.filter(difficulty_level='hieu').count(),
        'van_dung_thap': course_instance.question_set.filter(difficulty_level='van_dung_thap').count(),
        'van_dung_cao': course_instance.question_set.filter(difficulty_level='van_dung_cao').count(),
    }
    return render(request, 'exam/admin_view_request.html', {'course_instance': course_instance, 'difficulty_data': difficulty_data})


@login_required(login_url='adminlogin')
def view_all_questions(request, course_id):
    # Lấy đối tượng Course
    course_instance = models.Course.objects.get(id=course_id)

    # Lấy tất cả câu hỏi của khóa học
    questions = models.Question.objects.filter(course=course_instance)

    # Truyền câu hỏi và đánh giá vào template
    return render(request, 'exam/view_all_questions.html', {'course_instance': course_instance, 'questions': questions})

# Thêm YCCĐ vào start exam
@login_required(login_url='adminlogin')
def add_exam_content_view(request):
    examcontentForm = ExamContentForm()
    if request.method == 'POST':
        examcontentForm = ExamContentForm(request.POST)
        if examcontentForm.is_valid():
            content = examcontentForm.save(commit=False)
            course_id = request.POST.get('courseID')  # Lấy course_id từ POST data
            course = models.Course.objects.get(id=course_id)
            content.course = course
            content.save()
            return HttpResponseRedirect('/admin-view-question')  # Chuyển hướng đến trang danh sách câu hỏi
        else:
            print("Form is invalid")

    return render(request, 'exam/add_exam_content_view.html', {'examcontentForm': examcontentForm})

#Xem YCCĐ
@login_required(login_url='adminlogin')
def view_exam_content_view(request):
    contents= models.ExamContent.objects.all()
    courses= models.Course.objects.all()
    return render(request,'exam/view_exam_content_view.html',{'contents':contents,'courses': courses})

#Xem trang YCCĐ để xóa
@login_required(login_url='adminlogin')
def view_delete_content(request, course_id):
    # Lấy đối tượng Course
    course_instance = models.Course.objects.get(id=course_id)
    # Truy vấn tất cả các bản ghi từ mô hình ExamContent, lọc theo course.
    contents=models.ExamContent.objects.filter(course = course_instance)
    return render(request, 'exam/view_delete_content.html', {'contents': contents,'course_instance': course_instance})

#xóa YCCĐ
@login_required(login_url='adminlogin')

templates/exam/add_exam_content_view.html
{% extends 'exam/adminbase.html' %}
{% load widget_tweaks %}
{% block content %}

<style>
    .container {
        max-width: 600px;
        margin: auto;
    }

    .jumbotron {
        background-color: #f8f9fa;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1 {
        color: dark;
    }

    label {
        display: block;
        margin-bottom: 5px;
        font-weight: bold;
    }

    input, button {
        width: 100%;
        padding: 10px;
        margin-bottom: 15px;
        box-sizing: border-box;
    }

    button {
        background-color: #007bff;
        color: #fff;
        cursor: pointer;
        border: none;
        border-radius: 5px;
    }

    button:hover {
        background-color: #0056b3;
    }

    /* Thêm kiểu cho lỗi validation */
    .error-message {
        color: #dc3545;
        margin-top: 5px;
    }
</style>

<div class="container my-4">
    <div class="jumbotron">
        <h1 class="display-4 text-center">Thêm Nội Cần Đạt</h1>
        <form method="post">
            {% csrf_token %}
            <label for="id_exam_requirement">Yêu cầu cần đạt:</label>
            {{ examcontentForm.exam_requirement|attr:'required:true' }}
            <span class="error-message">{{ examcontentForm.exam_requirement.errors }}</span>

            <label for="id_courseID">Tên khóa học:</label> {{ examcontentForm.courseID|attr:'required:true' }}
            <span class="error-message">{{ examcontentForm.courseID.errors }}</span>
            <button type="submit" class="btn btn-dark" style="border-radius:0px;">Lưu</button>
        </form>
    </div>
</div>
{% endblock content %}

templates/exam/admin_question.html
{% extends 'exam/adminbase.html' %}
{% load widget_tweaks %}
{% block content %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link  href="https://th.bing.com/th/id/OIP._2unhUk9v8d-QsxMjcKMxgHaDm?rs=1&pid=ImgDetMain.png" rel="shortcut icon">
    <style type="text/css">
      a:link {
        text-decoration: none;
      }
  
      .order-card {
        color: rgb(255, 255, 255);
      }
  
      .bg-c-blue {
        background: #104f66;
      }
  
      .bg-c-gtx {
        background:#303a3c;
      }
  
      .bg-c-yellow {
        background: #53616e;
      }
  
      .bg-c-pink {
        background: #663a30;
      }
  
  
      .card {
        
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
      }
  
      .card .card-block {
        padding: 25px;
      }
  
      .order-card i {
        font-size: 26px;
      }
  
      .f-left {
        float: left;
      }
  
      .f-right {
        float: right;
      }
      header {
      left: 0px;
      right: 0px;
    }
    </style>
  </head>
<br><br>

  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xl-6">
        <a href="admin-add-question" style="text-decoration: none;color:white;">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20"> Thêm câu hỏi </h6>
            <h2 class="text-right"><i class="fas fa-plus f-left"></i></h2>
          </div>
        </div>
      </a>
      </div>
  
      <div class="col-md-4 col-xl-6">
        <a href="admin-view-question" style="text-decoration: none;color:white;">
        <div class="card bg-c-gtx order-card">
          <div class="card-block">
            <h6 class="m-b-20">Xem câu hỏi</h6>
            <h2 class="text-right"><i class="fas fa-eye f-left"></i></h2>
          </div>
        </div>
      </a>
      </div>
  
      <div class="col-md-4 col-xl-6">
        <a href="add-exam-content-view" style="text-decoration: none; color: white;">
            <div class="card bg-c-blue order-card">
                <div class="card-block">
                    <h6 class="m-b-20">Thêm yêu cầu cần đạt</h6>
                    <h2 class="text-right"><i class="fas fa-plus f-left"></i></h2>
                </div>
            </div>
        </a>
    </div>
    <div class="col-md-4 col-xl-6">
      <a href= "view-exam-content-view"  style="text-decoration: none;color:white;">
      <div class="card bg-c-gtx order-card">
        <div class="card-block">
          <h6 class="m-b-20">Xem yêu cầu cần đạt</h6>
          <h2 class="text-right"><i class="fas fa-eye f-left"></i></h2>
        </div>
      </div>
    </a>
    </div>
  </div>
     
  

<br><br><br><br><br><br><br><br><br><br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>


{% endblock content %}

templates/exam/admin_student.html
{% extends 'exam/adminbase.html' %}
{% load widget_tweaks %}
{% block content %}


<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link  href="https://th.bing.com/th/id/OIP._2unhUk9v8d-QsxMjcKMxgHaDm?rs=1&pid=ImgDetMain.png" rel="shortcut icon">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <style type="text/css">
      a:link {
        text-decoration: none;
      }
  
      .order-card {
        color: rgb(255, 255, 255);
      }
  
      .bg-c-blue {
        background: #104f66;
      }
  
      .bg-c-gtx {
        background:#303a3c;
      }
  
      .bg-c-yellow {
        background: #53616e;
      }
  
      .bg-c-pink {
        background: #663a30;
      }
  
  
      .card {
        
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
      }
  
      .card .card-block {
        padding: 25px;
      }
  
      .order-card i {
        font-size: 26px;
      }
  
      .f-left {
        float: left;
      }
  
      .f-right {
        float: right;
      }
      header {
      left: 0px;
      right: 0px;
    }
    </style>
  </head>
<br><br>

  <div class="container">
    <div class="row">
      <div class="col-md-4 col-xl-6">
        <a href="admin-view-student" style="text-decoration: none;color:white;">
        <div class="card bg-c-blue order-card">
          <div class="card-block">
            <h6 class="m-b-20"> Tổng số học sinh đăng ký </h6>
            <h2 class="text-right"><i class="fas fa-user-graduate f-left"></i><span>{{total_student}}</span></h2>
            
          </div>
        </div>
      </a>
      </div>
  
      <div class="col-md-4 col-xl-6">
        <a href="admin-view-student-marks" style="text-decoration: none;color:white;">
        <div class="card bg-c-gtx order-card">
          <div class="card-block">
            <h6 class="m-b-20">Điểm học sinh </h6>
            <h2 class="text-right"><i class="fas fa-sort-numeric-up f-left"></i><span><i class="fas fa-eye"></i></span></h2>
          </div>
        </div>
      </a>
      </div>

      <div class="col-md-4 col-xl-6">
        <a href= "{% url  'views_student' %}"  style="text-decoration: none;color:white;">
          <div class="card bg-c-blue order-card">
            <div class="card-block">
              <h6 class="m-b-20">Xem tiến độ </h6>
              <h2 class="text-right"><i class="fa-solid fa-bars-progress f-left"></i><span><i class="fas fa-eye"></i></span></h2>
            </div>
          </div>
        </a>  
      </div>
    </div>
  </div>
 

<br><br><br><br><br><br><br><br><br><br>

<script src="http://netdna.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>


{% endblock content %}

templates/exam/admin_view_marks.html
{% extends 'exam/adminbase.html' %}
{% block content %}
{% load static%}

<head>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link  href="https://th.bing.com/th/id/OIP._2unhUk9v8d-QsxMjcKMxgHaDm?rs=1&pid=ImgDetMain.png" rel="shortcut icon">
  <style media="screen">
    a:link {
      text-decoration: none;
    }

    h6 {
      text-align: center;
    }

    .row {
      margin: 100px;
    }
  </style>
</head>
<br><br>
<div class="container">
  <div class="panel panel-primary rounded-0">
    <div class="panel-heading rounded-0">
      <h6 class="panel-title">Bài kiểm tra</h6>
    </div>
    <table class="table table-hover table-bordered" id="dev-table">
      <thead>
        <tr >

          <th class="text-center">Tên bài kiểm tra</th>
          
          <th class="text-center">Hành động</th>
        </tr>
      </thead>
      {% for t in courses %}
      <tr>
        <td class="text-center"> {{t.course_name}}</td>
        <td class="text-center"><a class="btn btn-dark btn-sm" style="border-radius: 0%;" href="{% url 'admin-check-marks' t.id  %}"><span class="glyphicon glyphicon-eye-open"></span></a></td>
      </tr>
      {% endfor %}
    </table>
  </div>
</div>

<br><br><br><br><br><br>
{% endblock content %}